# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!

target 'BubblePop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'SteviaLayout', '~> 4.5.0'
  # pod 'SnapKit', '~> 5.0.0'
  # Pods for BubblePop

  target 'BubblePopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BubblePopUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
